import {
    readdirSync,
    readFileSync,
    statSync,
    writeFileSync,
    mkdirSync,
} from 'node:fs';
import { resolve, dirname, relative, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const distDir = resolve(here, '../node_modules/@neuralfog/elemix/dist');
const outFile = resolve(here, '../src/generated/elemix-dts.ts');

const collect = (dir, acc = []) => {
    for (const entry of readdirSync(dir)) {
        const full = join(dir, entry);
        if (statSync(full).isDirectory()) {
            if (entry === 'test') continue;
            collect(full, acc);
        } else if (entry.endsWith('.d.ts') && !entry.endsWith('.test.d.ts')) {
            acc.push(full);
        }
    }
    return acc;
};

const files = collect(distDir);
const pkgRoot = 'node_modules/@neuralfog/elemix';

const lib = {};
for (const file of files) {
    const rel = relative(distDir, file).replaceAll('\\', '/');
    lib[`${pkgRoot}/${rel}`] = readFileSync(file, 'utf-8');
}

const subpaths = {
    '.': './index.d.ts',
    './runtime': './runtime.d.ts',
    './directives': './directives.d.ts',
    './types': './src/types.d.ts',
};

const pkgJson = {
    name: '@neuralfog/elemix',
    version: '0.0.0-playground',
    types: './index.d.ts',
    exports: Object.fromEntries(
        Object.entries(subpaths).map(([k, v]) => [k, { types: v }]),
    ),
};
lib[`${pkgRoot}/package.json`] = JSON.stringify(pkgJson, null, 2);

mkdirSync(dirname(outFile), { recursive: true });
writeFileSync(
    outFile,
    `// AUTO-GENERATED by scripts/gen-types.mjs — do not edit.
export const elemixDts: Record<string, string> = ${JSON.stringify(lib, null, 2)};
`,
);
console.log(
    `[gen-types] wrote ${Object.keys(lib).length} files -> ${relative(here, outFile)}`,
);
