import { execFileSync } from 'node:child_process';
import {
    existsSync,
    readdirSync,
    readFileSync,
    writeFileSync,
    copyFileSync,
    mkdirSync,
} from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const REPO = 'https://github.com/neuralfog/elemix.git';

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, '..');
const srcDir = resolve(root, 'elemix-src');
const pkgDir = resolve(srcDir, 'packages/elemix');
const bundleDir = resolve(pkgDir, 'bundle');
const distDir = resolve(pkgDir, 'dist');
const outDir = resolve(root, 'public/elemix');
const genDir = resolve(root, 'src/generated');

const args = new Set(process.argv.slice(2));
const update = args.has('--update') || args.has('-u');
const force = args.has('--force') || args.has('-f');

const run = (cmd, cmdArgs, cwd) =>
    execFileSync(cmd, cmdArgs, { cwd, stdio: 'inherit' });

let needsBuild = force;

if (!existsSync(srcDir)) {
    console.log(`[sync-elemix] cloning ${REPO}`);
    run('git', ['clone', '--depth', '1', REPO, srcDir], root);
    needsBuild = true;
} else if (update) {
    console.log('[sync-elemix] updating .elemix');
    run('git', ['-C', srcDir, 'pull', '--ff-only'], root);
    needsBuild = true;
}

if (!existsSync(bundleDir) || !existsSync(distDir)) needsBuild = true;

if (needsBuild) {
    console.log('[sync-elemix] installing elemix deps');
    run('pnpm', ['install', '--filter', '@neuralfog/elemix...'], srcDir);
    console.log('[sync-elemix] building bundle + types');
    run('pnpm', ['--filter', '@neuralfog/elemix', 'run', 'build'], srcDir);
    run(
        'pnpm',
        ['--filter', '@neuralfog/elemix', 'run', 'build:bundle'],
        srcDir,
    );
}

const bundle = readdirSync(bundleDir).find((f) => f.endsWith('.js'));
if (!bundle) {
    console.error('[sync-elemix] no bundle produced in packages/elemix/bundle');
    process.exit(1);
}

mkdirSync(outDir, { recursive: true });
copyFileSync(resolve(bundleDir, bundle), resolve(outDir, 'elemix.js'));
console.log(`[sync-elemix] ${bundle} -> public/elemix/elemix.js`);

const pkg = JSON.parse(readFileSync(resolve(pkgDir, 'package.json'), 'utf-8'));
mkdirSync(genDir, { recursive: true });
writeFileSync(
    resolve(genDir, 'elemix-meta.ts'),
    `// AUTO-GENERATED by scripts/sync-elemix.mjs — do not edit.
export const ELEMIX_NAME = ${JSON.stringify(pkg.name)};
export const ELEMIX_VERSION = ${JSON.stringify(pkg.version)};
`,
);
console.log(`[sync-elemix] ${pkg.name} v${pkg.version}`);
