import {
    copyFileSync,
    mkdirSync,
    readFileSync,
    readdirSync,
    rmSync,
    writeFileSync,
} from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

// Elemix ships as an npm dependency now — this just stages its browser ESM for
// the preview iframe. Bump the version with `pnpm add @neuralfog/elemix@<v>`.
const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, '..');
const pkgDir = resolve(root, 'node_modules/@neuralfog/elemix');
const distDir = resolve(pkgDir, 'dist');
const outDir = resolve(root, 'public/elemix');
const genDir = resolve(root, 'src/generated');

const pkg = JSON.parse(readFileSync(resolve(pkgDir, 'package.json'), 'utf-8'));

// Fresh-copy the browser ESM: the entry modules (`index/runtime/directives.mjs`)
// plus the shared `.js` chunks they import. The import map (see preview.ts) maps
// each entry specifier; the browser resolves the relative `./chunk` imports
// against these files, so the shared reactive core loads ONCE and its singletons
// stay shared across every entry.
rmSync(outDir, { recursive: true, force: true });
mkdirSync(outDir, { recursive: true });
let copied = 0;
for (const file of readdirSync(distDir)) {
    if (file.endsWith('.mjs') || file.endsWith('.js')) {
        copyFileSync(resolve(distDir, file), resolve(outDir, file));
        copied++;
    }
}
console.log(`[sync-elemix] copied ${copied} files -> public/elemix/`);

mkdirSync(genDir, { recursive: true });
writeFileSync(
    resolve(genDir, 'elemix-meta.ts'),
    `// AUTO-GENERATED by scripts/sync-elemix.mjs — do not edit.
export const ELEMIX_NAME = ${JSON.stringify(pkg.name)};
export const ELEMIX_VERSION = ${JSON.stringify(pkg.version)};
`,
);
console.log(`[sync-elemix] ${pkg.name} v${pkg.version}`);
